### PR TITLE
fix: properry dialog shows 1 extra number

### PR DESCRIPTION
**Pull request by SiamSami**
Before:
DeepinScreenshot_dde-desktop_20190720231552
After:
DeepinScreenshot_dde-desktop_20190721111410

### CODE REVIEW

**Comment by BLumia** [comment]
Hi and I'll try to discuss with PM about this issue later. Would like to close it for now since before that I cannot merge it, I'm able to reopen and merge it once we get agree about this issue and I'll let you know about any news about this issue.

Thanks for the patch again!

**Comment by BLumia** [comment]
Hi and a catch-up for this issue, this should be fixed in v20 release, please keep an eye on it :)

**Comment by SiamSami** [comment]
When will v20 be released?

**Comment by BLumia** [comment]
> When will v20 be released?

Sorry I don't know :/

**Pull request closed without merging**
