### PR TITLE
fix: Asking password dialog for sftp which is not shown at center

### PR DESCRIPTION
**Pull request by shzhuangpub**
Call the moveToCenter() function of the dialog.

### CODE REVIEW

**Review by itsXuSt — COMMENTED** [review]
确认双屏是否 OK

**Comment by shzhuangpub** [comment]
> 确认双屏是否 OK

经测试，OK的。

**Review by GongHeng2017 — APPROVED** [review]
/approve

**Review by max-lvs — APPROVED** [review]

**Pull request merged**
