### PR TITLE
fix:Mark name. After the second time, the input box loses focus and the mark fails

### PR DESCRIPTION
**Pull request by liyigang1**
1. On the desktop, select a file, right-click the mark, and enter a character in the input box. The mark is successful if the focus is lost. 2. Continue to right-click the mark, and enter a character in the input box to lose the focus (click other places, do not click the current file)

Log: fix a focus-lose issue
Bug: https://pms.uniontech.com/bug-view-165655.html

### CODE REVIEW

**Review by misonlan — DISMISSED** [review]

**Review by itsXuSt — CHANGES_REQUESTED** [review]
commit title 太长。

**Review by itsXuSt — DISMISSED** [review]

**Comment by itsXuSt** [comment]
虽然我还是觉得标题很长

**Review by obslee — APPROVED** [review]

**Review by max-lvs — APPROVED** [review]

**Pull request merged**
