### PR TITLE
fix: [preview] update music preview UI

### PR DESCRIPTION
**Pull request by GongHeng2017**
as title

Log: update music preview UI
Bug: https://pms.uniontech.com/bug-view-157251.html

### CODE REVIEW

**Review by max-lvs — DISMISSED** [review]
+2

**Comment by Kakueeen** [comment]
+1

**Review by max-lvs — APPROVED** [review]
+2

**Review by Lighto-Ku — COMMENTED** [review]
+1

吐槽一下，这个cover类命名有点抽象了。

**Pull request merged**
