### PR TITLE
fix: build failures under Qt 5.15

### PR DESCRIPTION
**Pull request by felixonmars**
The includes are missing here.

Log:

### CODE REVIEW

**Comment by cheese** [comment]
Fedora needs this fix too.

**Comment by juteman** [comment]
hello, pull request has conficting files.
please update.

**Review by deepinAdmin — DISMISSED** [review]
Approve merged, Will be auto merge

**Comment by felixonmars** [comment]
Updated. Hope the process won't take long or more conflicts may appear.

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 4:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 4:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 4:

cppcheck success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 5:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 5:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 5:

cppcheck success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

cppcheck success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1: Code-Review+1

[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1: Code-Review+1

[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by deepinAdmin — APPROVED** [review]
Approve merged, Will be auto merge

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 5: Code-Review+1

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

cppcheck success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 1:

cppcheck success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 2:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 2:

(5 comments)

代码注释率

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 2:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 2:

commit check success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 2:

cppcheck success!

**Review by deepinAdmin — COMMENTED** [review]
Patch Set 2:

cppcheck success!

**Review by deepinAdmin — APPROVED** [review]
Approve merged, Will be auto merge

**Review by deepinAdmin — APPROVED** [review]
Approve merged, Will be auto merge

**Pull request closed without merging**
