### PR TITLE
fix: Incorrectly dragging of filemanager

### PR DESCRIPTION
**Pull request by LiHua000**
fix: Drag-related events are not delivered correctly

Log: Incorrectly dragging of filemanager

Bug: https://pms.uniontech.com/bug-view-157731.html

### CODE REVIEW

**Comment by LiHua000** [comment]
recheck

**Comment by LiHua000** [comment]
recheck

**Comment by LiHua000** [comment]
recheck

**Review by Clauszy — CHANGES_REQUESTED** [review]
清楚自动格式化的无关提交

**Comment by LiHua000** [comment]
> 清楚自动格式化的无关提交

已改

**Comment by LiHua000** [comment]
re

**Comment by LiHua000** [comment]
recheck

**Comment by LiHua000** [comment]
> 清楚自动格式化的无关提交

**Comment by LiHua000** [comment]
recheck

**Comment by LiHua000** [comment]
recheck

**Comment by LiHua000** [comment]
recheck

**Pull request closed without merging**
