### PR TITLE
feat: Add riscv64 support

### PR DESCRIPTION
**Pull request by misaka00251**
Add riscv64 support

### CODE REVIEW

**Comment by misaka00251** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by misaka00251** [comment]
retest

**Comment by misaka00251** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by misaka00251** [comment]
retest

**Comment by misaka00251** [comment]
retest

**Comment by BLumia** [comment]
Hi，commitlint 检查是要求 commit 除了 Subject 一行外，还需要有内容的，比如

```
feat: Add riscv64 support

增加 RiscV 64 支持
```

amend 一下提交然后覆盖掉这个 PR 里的版本就可以通过 commitlint 了~

**Review by Zeno-sole — APPROVED** [review]

**Review by BLumia — APPROVED** [review]

**Pull request merged**
