### PR TITLE
Disable dmr in arm64

### PR DESCRIPTION
**Pull request by hillwoodroc**

### CODE REVIEW

**Comment by BLumia** [comment]
Hi and may I know the reason of this patch? The internal CI did package on arm64 and currently we haven't got bug report about the video preview plugin. Thanks.

**Comment by hillwoodroc** [comment]
Deepin Movie can't be built on openSUSE arm64. I guess it doesn't support arm64. So I think we should disable this option on arm64

**Comment by BLumia** [comment]
Maybe we can wait for v20 release and see if the released deepin-movie can build under arm64, if still failed, we'll discuss what should we do next :)

**Comment by MCredbear** [comment]
> Deepin Movie can't be built on openSUSE arm64. I guess it doesn't support arm64. So I think we should disable this option on arm64

nope，I built it successfully on debian arm64.and debian's repository also has dmr's packages

**Pull request closed without merging**
